[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "litegs"
version = "0.0.0"
description = "LiteGS environment"
requires-python = ">=3.12"
dependencies = [
  "torch==2.5.1",
  "torchvision==0.20.1",
  "torchaudio==2.5.1",
  "torchmetrics",
  "plyfile",
  "tqdm",
  "pillow",
  "opencv-python",
  "matplotlib",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["litegs*"]

[tool.uv.sources]
simple_knn = { path = "litegs/submodules/simple-knn" }
fused_ssim = { path = "litegs/submodules/fused_ssim" }
litegs_fused = { path = "litegs/submodules/gaussian_raster" }

[tool.uv.pip]
no-build-isolation = true

[tool.litegs.cuda]
version = "12.4"

[tool.litegs.torch]
index-url = "https://download.pytorch.org/whl/cu124"
